# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'MainApp.xcworkspace'
use_frameworks!

def generator_pods
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.5'
  pod 'OneTimePassword', '~> 3.2'
  pod 'SwiftyRSA', git: 'https://git.rarolabs.com.br/bmg/SwiftyRSA.git'
end

target 'MainApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MainApp
  generator_pods

end

target 'OTPGenerator' do
  project '../OTPGenerator/OTPGenerator.xcodeproj'
  
  generator_pods
end
